//just a file full of useful bits and bobs that aren't built into javascript by default.
const sleep = (delay) => new Promise((resolve) => setTimeout(resolve, delay)); //why doesn't js have a wait function by default...

